version: "3"
services:
   web:
      image: filtrast/top
      ports:
      - "5000:5000"
   
   es:
      image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
      container_name: es
      environment:
      - discovery.type=single-node
      ports:
      - 9200:9200
